name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  check:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  build_linux:
    needs: check
    name: Build for Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}-windows-amd64
          path: build/bin/${{ inputs.name }}-amd64.exe

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}-linux-amd64
          path: build/bin/${{ inputs.name }}-linux-amd64

  build_macos:
    needs: check
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}-darwin-arm64
          path: build/bin/${{ inputs.name }}-arm64.app/

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}-darwin-amd64
          path: build/bin/${{ inputs.name }}-amd64.app/
